apiVersion: apps/v1
kind: Deployment
metadata:
  name: grecko
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grecko
  template:
    metadata:
      labels:
        app: grecko
    spec:
      containers:
      - name: grecko
        image: tannuahuja14/grecko:${GIT_COMMIT}
        ports:
        - containerPort: 8080
